### ISSUE TITLE
INSaFLU failed to build

### ISSUE THREAD

**Issue by hatimalmutairi** [INSaFLU/docker#10]
Hi [INSaFLU Contributors](https://github.com/INSaFLU/docker/graphs/contributors), 
I'v been trying to follow the installation [guide](https://github.com/INSaFLU/docker#readme),  and when every time I reach the step:
 ```sh
## build INSaFLU
$ ./build.sh
$ ./up.sh
```
the terminal gives me the error: 
```sh
#0 42.37 W: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
#0 42.37 E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/dists/stretch-pgdg/10/binary-amd64/Packages  404  Not Found
#0 42.37 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: executor failed running [/bin/sh -c apt-get update       && apt install -y --no-install-recommends            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR            postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR-scripts            postgis       && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

It seems to me that it requests version 10 of  [PostgreSQL](https://www.postgresql.org/)  from ```http://apt.postgresql.org/pub/repos/apt stretch-pgdg```
However I think it should requests it from ```http://apt.postgresql.org/pub/repos/apt/ focal-pgdg``` 

my machine info:
```sh
Ubuntu 20.04.4 LTS
Docker version 20.10.21
```
So, is there anyway to resolve this? 

Thanks,
Hatim

**Comment by dsobral** [comment]
Dear Hatim,

The Dockerfile was already quite old, and the LTS of Debian Stretch (used in the image it depends on) ended in July 2022.
Apparently the stretch repository disappeared completely, so it is generating an error.

I've tweaked the Dockerfile to at least be in a version where the repository exists.
I did a small test and it seemed to work.
Let me know if it works for you now.

Best,
Daniel

**Comment by hatimalmutairi** [comment]
Hi Daniel, 
Thank for making the changes. 
However, I've found another broken line upon building for the second time. 
in line 196 in  [install.sh](https://github.com/INSaFLU/docker/blob/master/components/insaflu-server/install.sh)
```sh
### prokka
echo "Install prokka"
cd /software && git clone --branch v1.12 https://github.com/tseemann/prokka.git && cd extra_software && wget -O tbl2asn.gz ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz && gunzip tbl2asn.gz && chmod +x tbl2asn && mv tbl2asn /software/prokka/binaries/linux
if [ $? -ne 0 ]; then
    echo "Error installing prokka"
    exit 1
fi
```
tbl2asn is now cannot  downloded using ```ftp://``` link. instead it should be replaced with ```https://```

Thanks again, 
Hatim

**Comment by dsobral** [comment]
The ftp:// link should work (I just tested). In this case, it may have been a temporary glitch in the connection (or eventually a limitation of your network). Since INSaFLU requires many downloads, it may occasionally fail at some point.

You can change ftp:// to https:// in your local install.sh if it works better for you.

We will change the URLs at some point.

Best,
Daniel
