### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by AleksanderRing** [INSaFLU/docker#18]
I've tried to install the insaflu docker according to the steps described here: https://github.com/INSaFLU/docker, but I've experienced two issues. 
  
1)

11 1034.0 --2023-06-13 07:29:35--  ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz
11 1034.0   (try:20) => 'tbl2asn.gz'
11 1034.0 Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|2607:f220:41e:250::12|:21... failed: Cannot assign requested address.
11 1034.0 Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|2607:f220:41e:250::13|:21... failed: Cannot assign requested address.
11 1034.0 Giving up.
11 1034.0 
11 1034.0 Error installing prokka
failed to resolve: process "/bin/sh -c sh /tmp_install/install_software.sh" did not complete successfully: exit code:1

2)

27 1038.8   Non-zero exit status: 1 
27 1038.8 Files=334, Tests=17143, 87 wallclock secs ( 4.54 usr  0.99 sys + 79.52 cusr  6.10 csys = 91.15 CPU)
27 1038.8 Result: FAIL
27 1038.8 Failed 2/334 test programs. 1/17143 subtests failed.
27 1040.4   CJFIELDS/BioPerl-1.6.924.tar.gz
27 1040.4   ./Build test -- NOT OK
27 1040.4 //hint// to see the cpan-testers results for installing this module, try:
27 1040.4   reports CJFIELDS/BioPerl-1.6.924.tar.gz
failed to solve: executor failed running [/bin/sh -c sh /tmp_install/install.sh]: exit code: 1

I can provide the entire output or additional inormation on request, but to begin with I'd like to know if anyone has an idea to solve these

Best regards
Aleks

**Comment by AleksanderRing** [comment]
Thanks for your quick reply

I tested the ftp ncbi connection and indeed the connection is refused. I'll contact my IT department and see if they can solve the issue. 
Can you point me in the right direction for getting the docker to install from a local instance of tblasn? Where should I start? 


Best,
Aleks

**Comment by dsobral** [comment]
Before doing this I would advice you to make a pull of the docker repository as there was a very recent change in the code.
https://insaflu.readthedocs.io/en/latest/change_log.html 

First, download linux64.tbl2asn.gz and unzip it. You should get the file tbl2asn.linux64
Copy the tbl2asn.linux64 file into the folder components/insaflu-server/software/

Now, you need to edit the file  components/insaflu-server/install_software.sh
(you can edit using any text editor such as Notepad++)

Namely change the line to install prokka to:
cd /software && git clone --branch v1.12 https://github.com/tseemann/prokka.git && mv /tmp_install/software/tbl2asn.linux64  
 /software/prokka/binaries/linux/tbl2asn && chmod a+x  /software/prokka/binaries/linux/tbl2asn

Now you can build.

I have not tested this yet, but it should solve at least the issue with downloading from ncbi.

Let me know how it goes.

Daniel

**Comment by AleksanderRing** [comment]
Thank you very much, it worked!

New issue: After I use ./up.sh and go to 127.0.0.1:<port defined in .env> I get 503 unavailable service. 

I can provide a full output and screenshots on request, but to begin with I'd like to know if you have an idea on how to solve it 


Best,
Aleks

**Comment by dsobral** [comment]
Good to hear. 

You should now be at the same stage as what was described in #22 

This usually fixes it for me:

ctrl^c
chmod -R 777 $BASE_PATH_DATA/insaflu/log [where $BASE_PATH_DATA is the folder you defined in .env]
.> /up.sh
If you want the service to run in the background, instead of up.sh just do:
docker compose up insaflu-server -d

If you see a 400 error, this means you are not running in localhost and need to change the .env file by adding the IP of your machine (in this case it seems to be 10.101.34.77) in the ALLOWED_HOSTS field and restart the containers.

Hope it helps,
Daniel

**Comment by AleksanderRing** [comment]
Thanks very much, it works now!

Again a new question: How do I run the televir module? 
I ran ./up_televir.sh and I get a exit code 0 so that looks good to me. Is it supposed to appear on the insaflu dashbord like the https://insaflu.insa.pt/ site or should I run it seperately? I might have missed something obvious here.


Best regards,
Aleks

**Comment by dsobral** [comment]
Great, thanks for your patience.

I am assuming you ran ./up_televir.sh before running ./up.sh
up_televir.sh will launch a machine that only installs televir and then finishes.
It should have taken several hours to install. If it ran very quickly then it is unlikely to have installed correctly.

After up_televir finishes, when you run ./up.sh the televir module should appear on the dashboard like in the public website.
If it does not appear, then there is something wrong.  
Hopefully, it will be something simple to solve.
It may be just a misplaced file.

Let me know if televir does not show up.

Thanks,
Daniel

**Comment by AleksanderRing** [comment]
And thank you for your patience : )

I ran ./up first to test is everything would build properly. Insaflu is now running on the IP:PORT address I want. Then I ran ./up_televir.sh to include it in the now running local insaflu server. It took many hours to run ./up_televir, so I think all is done correctly. 
I've tried to stop the insaflu docker with ^c  ./stop and the ./up again, but televir is not included.
Do I have to run ./up_televir before ./up for it to be included or can is there a way to include it as is now? Is there a way I can test if ./up_televir ran correctly? 
I can try to re install everything again to see if it makes a difference, but since it takes time I would prefer to try other options first. 

Best regards,
Aleks

**Comment by dsobral** [comment]
The Televir installation writes a log that should be in '/televir/mngs_benchmark/utility_docker.db'

Go inside the insaflu-server container and check if the file is there.
> docker exec -it insaflu-server bash
> ls /televir/mngs_benchmark/

If you don't have the file 'utility_docker.db', do you have another file, 'utility.db'?
If you have 'utility_db' just copy utility.db' to 'utility_docker.db'
> cp /televir/mngs_benchmark/utility.db /televir/mngs_benchmark/utility_docker.db

If you have the utility_docker.db file (even if you just copied it), run the following:
> cd /insaflu_web/INSaFLU
> python3 manage.py generate_default_trees
> ../commands/restart-apache

Hopefully now Televir will appear in the dashboard.

If you don't have any utility file at all, then the televir installation did not run and you most probably need to install it again with the up_televir.sh.

Best,
Daniel

PS:
We're well aware that installing this is still cumbersome.
We'll try to have ready-to-use images available to avoid having to build everything from scratch everytime.

**Comment by AleksanderRing** [comment]
Hi

Unfortunately it didn't work. I have both utility files utility_docker.db and utility.db, and I have tried both approaches, with and without copying to utility.db, and then ./restart-apache, but televir is still not there. 

I also tried reinstalling the insaflu docker, but it seems to me as if it doesn't recognize that televir is installed.  

Any thoughts or things I can try? Please tell me if you need content from files or if you need outputs or similar. 

Best,
Aleks

**Comment by dsobral** [comment]
Hello Aleks,

Sorry to hear you're still having problems.

We have detected a potential issue.
Hopefully the solution will be relatively straightforward and you won't have to reinstall everything again.

We'll post the solution here as soon as possible.

Thanks,
Daniel

**Comment by SantosJGND** [comment]
Hello Aleksander,

Sorry for the late reply.

**Comment by AleksanderRing** [comment]
Hello Joao

I tried all the steps but it did not work. I tried to remove everything and start over.

Am not experienced with docker so I don't know if I'm doing it right.

I've tried to remove everything with docker system prune, rm -rf docker, docker rmi <images relating to insaflu>, 
docker builder prune. (should I do more or something else?)

and then reinstalling everything using the installation guide https://github.com/INSaFLU/docker 

./build.sh completes without errors however I get an error with ./up_televir.sh 

* Error response from daemon: open /home/xpto/INSaFLU/data/postgres/postgres_data: no such file or directory

This was not an issue before. I've used the default basepath with previous attempts with no issues.

Can I have missed somthing? I can provide outputs etc. on request. Can there be some legacy data or something I'm not aware of? 
What steps can I take from here? 

Best regards,
Aleks

**Comment by dsobral** [comment]
Dear Aleks,

I've noticed that ./up_televir.sh does not contain folder creation.
So the container complains that the folder does not exist.

I've added those steps to the docker now.
If you update (pull) the repository and run ./up_televir.sh, the folders should be created if they do not exist.

Previously the folders would be created automatically if they didn't exist but this behavior seems to have changed so now we added an extra step of creating the folders in the up script (but I forgot to add those to up_televir, sorry).
You can look inside the up.sh script to see which folders are created if you want to check them manually.

Hope this helps.

Regards,
Daniel

**Comment by AleksanderRing** [comment]
Dear Daniel

I had to add source .env to the ./up_televir.sh file, but it build now.

But still no televir in the browser. I've added a folder with various outputs for you to see, maybe I'm missing something in the process.
[docker_out.zip](https://github.com/INSaFLU/docker/files/12180220/docker_out.zip)


Best regards,
Aleks

**Comment by AleksanderRing** [comment]
This issue is resolved, so feel free to close it : )

Best regards
Aleks

**Comment by dsobral** [comment]
Sorry for the delay in replying.
Glad you could solve the issue.

You probably noticed that you just needed to change some variables defined in the configuration file:

It is in the documentation, although we need to make it clearer:
You can customize your environment. Some of the relevant variables include the maximum reads size for upload (e.g., MAX_FASTQ_FILE_UPLOAD = 104857600), indicate if the files should be (or not) downsized after upload (i.e., DOWN_SIZE_FASTQ_FILES = True/False), indicate the maximum files size after downsizing (e.g. MAX_FASTQ_FILE_WITH_DOWNSIZE = 429916160), maximum length of external consensus sequences for nextstrain analysis (eg. MAX_LENGTH_SEQUENCE_TOTAL_FROM_CONSENSUS_FASTA = 104857600), etc.

Do not hesitate to ask any question.

Thanks,
Daniel
