### ISSUE TITLE
Prokka causing problem to insaflu

### ISSUE THREAD

**Issue by muzzamil1234** [INSaFLU/docker#20]
i am getting this error, while running insaflu using docker.

nsaflu-server  | Running migrations:
insaflu-server  |   No migrations to apply.
insaflu-server  | ---> Load default files  ...
insaflu-server  | ---> Set prokka default databases  ...
insaflu-server  | "uniq" is not exported by the List::Util module
insaflu-server  | Can't continue after import errors at /software/prokka/bin/prokka line 31.
insaflu-server  | BEGIN failed--compilation aborted at /software/prokka/bin/prokka line 31.
insaflu-server exited with code 0

**Comment by dsobral** [comment]
Hello,

I never had that error, and I very recently did a fresh build.

Somehow the Perl that gets installed is a different version (possibly older) than what it should be for prokka.
I'll try to see if I can force a certain repository that always guarantees that the correct version is installed.

We're also aiming to provide a self-contained pre-built image as soon as possible. 
This should obviate the need to build from scratch every time.

Best,
Daniel

**Comment by muzzamil1234** [comment]
Thanks.
