### ISSUE TITLE
Insaflu is not running

### ISSUE THREAD

**Issue by muzzamil1234** [INSaFLU/docker#25]
Hello, hope you are doing well. my standalone insaflu was running fine, but today when i start insaflu i am facing this issue.
![Screenshot from 2023-07-11 15-07-12](https://github.com/INSaFLU/docker/assets/137260213/8fde909c-0613-432f-8322-30c1d1efdbfb)

**Comment by SantosJGND** [comment]
Hello @muzzamil1234,

I'm sorry for this complication. 

For a bit of context, can i ask you a couple of questions:
- when did you first build the insaflu-server?
- did you run up_televir.sh prior to this error? 
- did you use the standalone app with or without televir before this error? 

thank you, 
Joao

**Comment by muzzamil1234** [comment]
Hi SantosJGND , Thanks for quick reply 
i build one week ago, yes i run up_televir.sh prior to this error and yes i used standalone app wiithout televir before this error.

**Comment by SantosJGND** [comment]
Hello @muzzamil1234,

Sorry for the late reply this time, have been trying to find a clean solution but am not able to reproduce this problem. Could I ask an additional question: 
- did you have the app running during the build? (trying to pin down how those duplicate entries got saved).

as it is we can propose two courses of action, (both of which first depend on stopping all containers first, using ./stop.sh):

### A. resetting software parameters - does not delete results, but more convoluted.
i - in the docker-compose file, in the insaflu-server section, change `restart: on-failure` to `restart: no` (this will allow you to access the container despite the above crash).
ii. run ./up.sh; enter the container - `docker exec -it insaflu-server /bin/bash`
iii. Change directory to /insaflu_web/INSaFLU;
iv. enter the django shell: `python3 manage.py shell`, 
v. run the following lines:

``` python 
from settings.default_software import DefaultSoftware
from django.contrib.auth.models import User
default_software= DefaultSoftware()
default_software.reset_user_software(User.objects.all())
```

note: this will clear any project specific settings. A series of logs are printed.

vi. exit the shell, exit container, re-run ./stop.sh.
vii. run ./up.sh. you should be good to go. 

### B. A bit more drastic - delete all db data, rebuild. will delete existing results.
i. Delete the contents of the postgres directory. According to the .env file you setup on installation, this will be: `$BASE_PATH_DATA/postgres/`. as such, the command should be:

```bash
sudo rm -r $BASE_PATH_DATA/postgres/*
```

ii. run ./up.sh.

the error should be clear.

Please tell us how this goes, and thank you for your patience. 
Best, 
Joao
