### ISSUE TITLE
Service unavailable 

### ISSUE THREAD

**Issue by muzzamil1234** [INSaFLU/docker#26]
Hello Dear, Hope you are doing well my insaflu server is not running after building this error i am facing.

![Screenshot from 2023-08-24 09-54-52](https://github.com/INSaFLU/docker/assets/137260213/69da9d68-459a-4a42-a1c7-b168c64fc18b)

![Screenshot from 2023-08-24 09-55-22](https://github.com/INSaFLU/docker/assets/137260213/60f1a5c2-2565-44e5-b5d0-df27e27b9aae)
![Uploading Screenshot from 2023-08-24 09-54-52.png…]()
![Screenshot from 2023-08-24 10-03-51](https://github.com/INSaFLU/docker/assets/137260213/f0f6b829-b46f-49e8-831c-32b6bd6415be)

**Comment by dsobral** [comment]
Dear,

This is similar to another issue:
#22 

[you can simply try restarting the apache server]
> docker exec -it insaflu-server restart-apache

[if it doesn't work, usually, stopping the container, changing the permissions of some of the folders and restarting the container should work]:
> chmod -R 777 $BASE_PATH_DATA/insaflu/log  
[where $BASE_PATH_DATA is the folder you defined in .env]
> /up.sh

Hope this helps

Best,
Daniel
