### ISSUE TITLE
Upload size televir

### ISSUE THREAD

**Issue by AleksanderRing** [INSaFLU/docker#28]
Is it possible to change the max size of files for upload in the local install of the televir module?
![televir_size](https://github.com/INSaFLU/docker/assets/102508994/5631f7fb-3635-4c7e-8179-7264e2fde6ab)

If so how ? 

Best regards,
Aleks

**Comment by dsobral** [comment]
Sorry for the delay in replying.

That change is one of the reasons many people want to install the local version.

To change these definitions you need to change the .env file that is in the main INSaFLU folder:

`docker exec -it insaflu-server bash`
`nano /insaflu_web/INSaFLU/.env`
(you may need to install nano first: `yum install nano`)

Inside the .env you need to change the values of some variables eg.:
MAX_FASTQ_FILE_UPLOAD = xxx [add here a value that you want eg. 1Gb = 1048576000)

Other variables:
MAX_REF_FASTA_FILE=524280 [relevant for new references]
MAX_REF_GENBANK_FILE=1048576 [relevant for new references]
MAX_LENGTH_SEQUENCE_TOTAL_FROM_FASTA = 524280 [relevant for new references]
MAX_LENGTH_SEQUENCE_TOTAL_FROM_CONSENSUS_FASTA = 104857600  [relevant for nextstrain]
MAX_CONSENSUS_FASTA_FILE = 104857600 [relevant for nextstrain]

Then you need to restart apache for the configuration to take place:
`./insaflu_web/commands/restart-apache`

I hope this helps.
We need to make this step easier to perform, and make it clearer in the documentation.

Kind Regards,
Daniel

**Comment by dsobral** [comment]
My previous reply explains how do you change the configuration *after* installing INSaFLU.

You can/should setup the configuration before installing the software by editing the file:
https://github.com/INSaFLU/docker/blob/master/components/insaflu-server/configs/insaflu.env

**Comment by AleksanderRing** [comment]
Hi Daniel

Thanks for your reply. It worked : )

Best regards,
Aleks
