### ISSUE TITLE
Delete samples

### ISSUE THREAD

**Issue by AleksanderRing** [INSaFLU/docker#29]
I might have missed it, but I can't see how I can delete uploaded samples. I can delete projects, but not the uploaded samples

![buttons](https://github.com/INSaFLU/docker/assets/102508994/1d0a6e40-d6c5-4ed6-8751-271a1efceceb)

I probably just missed it. If it is not there, can it be added to the local docker ?

Best regards,
Aleks

**Comment by dsobral** [comment]
Samples can only be deleted IF they are not associated to any existing projects.
To be able to delete the samples, you first need to delete all the projects where the sample is included, or delete the sample from the projects.

Hope it helps,
Daniel

**Comment by AleksanderRing** [comment]
Hi Daniel,

Many of the samples you see don't have an associated project, but I don't see an option or button to delete them. 


Best regards
Aleks

**Comment by dsobral** [comment]
That's odd... when you upload a new sample, doesn't it have a delete button?

Daniel

**Comment by AleksanderRing** [comment]
I have deleted all projects now. So no samples can be tight to a project.
![no_projects](https://github.com/INSaFLU/docker/assets/102508994/6171143c-1c10-4f5a-82f0-096efdc74987)

But I don't see an option to delete the samples
![samples](https://github.com/INSaFLU/docker/assets/102508994/38a71d80-2ea4-4359-a4a9-5b8edfb44eda)

**Comment by dsobral** [comment]
It is hard to see what is going on, as I cannot reproduce the issue.

There seems to be some incoherence in the database that makes those samples "think" they are still associated to some (non-deleted) project.

That's why I asked if you could upload a new sample, to see if this happens again in a "fresh" sample.
If you don't have a fastq, you can for example download the fastq of one of the existing samples and reupload with a different sample name.

Kind Regards,
Daniel

**Comment by AleksanderRing** [comment]
I uploaded a new sample, and I could delete it. So I think you are right. 

Can you get an idea of how to fix this? just tell me if you need me to send anything, files output log, etc...


Best regards,
Aleks

**Comment by dsobral** [comment]
I don't know how that happened, and I had never seen that behavior before, so there's no specific code to correct it.

You can manually correct it by going directly to the django shell:
`
cd /insaflu_web/INSaFLU
python3 manage.py shell
`
Now you've entered the django shell.
This will allow you to manipulate all the django structures.

Then type something like this:
```
from managing_files.models import Sample
from django.contrib.auth.models import User

user = User.objects.get(username='insert_user_name')

all_samples = Sample.objects.all().filter(is_deleted=False, owner=user)
for sample in all_samples:
	sample.is_deleted = True
	sample.save()


```
This code will mark as deleted all samples of a given user that were not yet deleted. 


After adding new samples, and creating projects, try deleting projets to see if this happens again.

There's maybe some edge case related to the interaction between televir (viral discovery) and insaflu (genome-referece) projects.

Let us know.

Thanks,
Daniel

**Comment by AleksanderRing** [comment]
Hi Daniel

It seems to work now. Thank you very much : )


Best regards,
Aleks
